LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := egl.c
LOCAL_LDFLAGS := -L $(TARGET_OUT_VENDOR)/lib
LOCAL_LDLIBS := -lIMGegl_SGX$(SGX_CORE)_$(SGX_CORE_REV)
libEGL_POWERVR_SGX54X: $(TARGET_OUT_VENDOR)/lib/libIMGegl_SGX$(SGX_CORE)_$(SGX_CORE_REV).so
LOCAL_MODULE := libEGL_POWERVR_SGX54X

LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/lib/egl
LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)
